### ISSUE TITLE
File resolution different between python versions

### ISSUE THREAD

**Issue by wyoder** [nxt-dev/nxt#117]
**Describe the bug**
Python `3.9.7` does file resolution differently than python `3.10.8`. It's causing issues as graphs were built a specific way no longer work as expected.

**To Reproduce**
1. Unzip file attached
2. Open nxt
3. Open the nxt_test.nxt file
4. If you look at that file in `3.9.7` vs `3.10.8`, you will see on `/node.file_test` that the file resolves in one but not the other

**Expected behavior**
For it to resolve the same in both python versions

**Screenshots**
[nxt_example.zip](https://github.com/nxt-dev/nxt/files/14693218/nxt_example.zip)
https://github.com/nxt-dev/nxt/assets/4167012/ceb1c020-0b73-4374-85b9-ebcbf2f3341e

**Desktop (please complete the following information):**
 - OS: Windows 11
 - DCC Maya 2023.3 vs Maya 2024.2
 - Version: API v1.17

**Comment by ImLucasBrown** [comment]
Fixed by https://github.com/nxt-dev/nxt/commit/e2e338d901b085d22a83c401304848192aeb5c94
